### ISSUE TITLE
No WiFi or BT after going back to Stock FW

### ISSUE THREAD

**Issue by qnxt** [Redmi-Go/android_device_xiaomi_tiare#1]
Steps to reproduce:

0. Have an EMMC dump as a backup of your phone (highly recommended)
1. Build this like normal
2. flash it onto Redmi Go
3. use it or whatever
4. flash to the stock (fastboot or recovery, does not matter)

Expected result:
Everything on the phone should be working like it should on stock

Actual result:
WiFi and BT does not work. 
To fix, I had to restore the EMMC dump which should not be the case, since on other phones where lineage is official, this is never required to be done. Additionally, Xiaomi redistributes Stock ROMs officially with shell scripts that are supposed to restore the phone to it's stock condition. So this project should be compatible with that.

I think this replaces modem firmware or something that is normally not flashed by fastboot or recovery?

**Comment by techyminati** [comment]
* Reverting Back to Older Android Version ( ie, here, Android 11 to Android 8.1) Often corrupts persist, there are 2 solutions for it :- 
   - flash ``` persist.img ``` from stock rom
   - backup persist & restore it.
   
 Hope this helps !

**Comment by qnxt** [comment]
thank you!

**Comment by techyminati** [comment]
Welcome, Closed #1
